# Generated by Django 4.0 on 2022-01-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='related_words',
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_word', models.CharField(max_length=100)),
                ('rel_score', models.IntegerField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disparate_times.word')),
            ],
        ),
    ]
