# Generated by Django 4.0 on 2022-01-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0002_remove_word_related_words_relatedword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedWord',
        ),
    ]
