# Generated by Django 4.0 on 2022-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0003_delete_relatedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(),
        ),
    ]
