# Generated by Django 4.0 on 2022-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0007_alter_word_rel_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='rel_word',
            field=models.TextField(default='nothing yet'),
        ),
    ]
