# Generated by Django 4.0 on 2022-01-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0008_alter_word_rel_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_accessed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='times_accessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='written',
            field=models.DateField(null=True),
        ),
    ]
