# Generated by Django 4.0 on 2022-01-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0009_word_last_accessed_word_times_accessed_word_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='rel_score',
            field=models.IntegerField(default=1000),
        ),
    ]
