# Generated by Django 4.0 on 2022-01-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparate_times', '0010_word_rel_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='rel_score',
        ),
        migrations.AlterField(
            model_name='word',
            name='rel_word',
            field=models.TextField(default='{"word": "time", "score": "1000"}'),
        ),
    ]
